#pragma once
#include <discord-rpc/include/discord_rpc.h>
#include "stdafx.hpp"
#include <string_view>
#include <unordered_set>
#include "modules/ClientDLL.hpp"
#include "modules/HwDLL.hpp"
#include "cvars.hpp"
#include "hud_custom.hpp"

using namespace std::literals;

namespace discord_integration
{
		/**
		* Initializes the Discord integration. Call this once on BXT or game start.
		*/
		void initialize();

		/**
		* Call this in HUD_UpdateClientData.
		*/
		void on_update_client_data();

		/**
		* Call this in HUD_Frame.
		*/
		void on_frame();

		// Chapters
		const std::unordered_map<std::string_view, std::string> hl1_thumbnail_to_chapter = {
			{"hl1chapter1", "Anomalous Materials"},
			{"hl1chapter2", "Unforeseen Consequences"},
			{"hl1chapter3", "Office Complex"},
			{"hl1chapter4", "We've Got Hostiles"},
			{"hl1chapter5", "Blast Pit"},
			{"hl1chapter6", "Power Up"},
			{"hl1chapter7", "On A Rail"},
			{"hl1chapter8", "Apprehension"},
			{"hl1chapter9", "Residue Processing"},
			{"hl1chapter10", "Questionable Ethics"},
			{"hl1chapter11", "Surface Tension"},
			{"hl1chapter12", "Forget About Freeman"},
			{"hl1chapter13", "Lambda Core"},
			{"hl1chapter14", "Xen"},
			{"hl1chapter15", "Gonarch's Lair"},
			{"hl1chapter16", "Interloper"},
			{"hl1chapter17", "Nihilanth"},
			{"hl1chapter18", "Endgame"},
			{"hl1chapter19", "Hazard Course"},
			{"hl1chapter20", "Black Mesa Inbound"},
		};

		const std::unordered_map<std::string_view, std::string> hl1_map_name_to_thumbnail = {
			{"c1a0", "hl1chapter1"},
			{"c1a0a", "hl1chapter1"},
			{"c1a0b", "hl1chapter1"},
			{"c1a0d", "hl1chapter1"},
			{"c1a0e", "hl1chapter1"},
			{"c1a0c", "hl1chapter2"},
			{"c1a1", "hl1chapter2"},
			{"c1a1a", "hl1chapter2"},
			{"c1a1b", "hl1chapter2"},
			{"c1a1c", "hl1chapter2"},
			{"c1a1d", "hl1chapter2"},
			{"c1a1f", "hl1chapter2"},
			{"c1a2", "hl1chapter3"},
			{"c1a2a", "hl1chapter3"},
			{"c1a2b", "hl1chapter3"},
			{"c1a2c", "hl1chapter3"},
			{"c1a2d", "hl1chapter3"},
			{"c1a3", "hl1chapter4"},
			{"c1a3a", "hl1chapter4"},
			{"c1a3b", "hl1chapter4"},
			{"c1a3c", "hl1chapter4"},
			{"c1a3d", "hl1chapter4"},
			{"c1a4", "hl1chapter5"},
			{"c1a4b", "hl1chapter5"},
			{"c1a4d", "hl1chapter5"},
			{"c1a4e", "hl1chapter5"},
			{"c1a4f", "hl1chapter5"},
			{"c1a4g", "hl1chapter5"},
			{"c1a4i", "hl1chapter5"},
			{"c1a4j", "hl1chapter5"},
			{"c1a4k", "hl1chapter5"},
			{"c2a1", "hl1chapter6"},
			{"c2a1a", "hl1chapter6"},
			{"c2a1b", "hl1chapter6"},
			{"c2a2", "hl1chapter7"},
			{"c2a2a", "hl1chapter7"},
			{"c2a2b1", "hl1chapter7"},
			{"c2a2b2", "hl1chapter7"},
			{"c2a2c", "hl1chapter7"},
			{"c2a2d", "hl1chapter7"},
			{"c2a2e", "hl1chapter7"},
			{"c2a2f", "hl1chapter7"},
			{"c2a2g", "hl1chapter7"},
			{"c2a2h", "hl1chapter7"},
			{"c2a3", "hl1chapter8"},
			{"c2a3a", "hl1chapter8"},
			{"c2a3b", "hl1chapter8"},
			{"c2a3c", "hl1chapter8"},
			{"c2a3d", "hl1chapter8"},
			{"c2a3e", "hl1chapter8"},
			{"c2a4", "hl1chapter9"},
			{"c2a4a", "hl1chapter9"},
			{"c2a4b", "hl1chapter9"},
			{"c2a4c", "hl1chapter9"},
			{"c2a4d", "hl1chapter10"},
			{"c2a4e", "hl1chapter10"},
			{"c2a4f", "hl1chapter10"},
			{"c2a4g", "hl1chapter10"},
			{"c2a5", "hl1chapter11"},
			{"c2a5a", "hl1chapter11"},
			{"c2a5b", "hl1chapter11"},
			{"c2a5c", "hl1chapter11"},
			{"c2a5d", "hl1chapter11"},
			{"c2a5e", "hl1chapter11"},
			{"c2a5f", "hl1chapter11"},
			{"c2a5g", "hl1chapter11"},
			{"c2a5w", "hl1chapter11"},
			{"c2a5x", "hl1chapter11"},
			{"c3a1", "hl1chapter12"},
			{"c3a1a", "hl1chapter12"},
			{"c3a1b", "hl1chapter12"},
			{"c3a2", "hl1chapter13"},
			{"c3a2a", "hl1chapter13"},
			{"c3a2b", "hl1chapter13"},
			{"c3a2c", "hl1chapter13"},
			{"c3a2d", "hl1chapter13"},
			{"c3a2e", "hl1chapter13"},
			{"c3a2f", "hl1chapter13"},
			{"c4a1", "hl1chapter14"},
			{"c4a2", "hl1chapter15"},
			{"c4a2a", "hl1chapter15"},
			{"c4a2b", "hl1chapter15"},
			{"c4a1a", "hl1chapter16"},
			{"c4a1b", "hl1chapter16"},
			{"c4a1c", "hl1chapter16"},
			{"c4a1d", "hl1chapter16"},
			{"c4a1e", "hl1chapter16"},
			{"c4a1f", "hl1chapter16"},
			{"c4a3", "hl1chapter17"},
			{"c5a1", "hl1chapter18"},
			{"t0a0", "hl1chapter19"},
			{"t0a0a", "hl1chapter19"},
			{"t0a0b", "hl1chapter19"},
			{"t0a0b1", "hl1chapter19"},
			{"t0a0b2", "hl1chapter19"},
			{"t0a0c", "hl1chapter19"},
			{"t0a0d", "hl1chapter19"},
			{"c0a0", "hl1chapter20"},
			{"c0a0a", "hl1chapter20"},
			{"c0a0b", "hl1chapter20"},
			{"c0a0c", "hl1chapter20"},
			{"c0a0d", "hl1chapter20"},
			{"c0a0e", "hl1chapter20"},
		};

		const std::unordered_map<std::string_view, std::string> op4_thumbnail_to_chapter = {
			{"op4chapter1", "Welcome To Black Mesa"},
			{"op4chapter2", "We Are Pulling Out"},
			{"op4chapter3", "Missing In Action"},
			{"op4chapter4", "Friendly Fire"},
			{"op4chapter5", "We Are Not Alone"},
			{"op4chapter6", "Crush Depth"},
			{"op4chapter7", "Vicarious Reality"},
			{"op4chapter8", "Pit Worm's Nest"},
			{"op4chapter9", "Foxtrot Uniform"},
			{"op4chapter10", "The Package"},
			{"op4chapter11", "Worlds Collide"},
			{"op4chapter12", "Conclusion"},
			{"op4chapter13", "Boot Camp"},
			{"op4chapter14", "Incoming"},
		};

		const std::unordered_map<std::string_view, std::string> op4_map_name_to_thumbnail = {
			{"of1a1", "op4chapter1"},
			{"of1a2", "op4chapter1"},
			{"of1a3", "op4chapter1"},
			{"of1a4", "op4chapter1"},
			{"of1a4b", "op4chapter1"},
			{"of1a5", "op4chapter2"},
			{"of1a5b", "op4chapter2"},
			{"of1a6", "op4chapter2"},
			{"of2a1", "op4chapter3"},
			{"of2a1b", "op4chapter3"},
			{"of2a2", "op4chapter3"},
			{"of2a3", "op4chapter3"},
			{"of2a4", "op4chapter4"},
			{"of2a5", "op4chapter4"},
			{"of2a6", "op4chapter4"},
			{"of3a1", "op4chapter5"},
			{"of3a1b", "op4chapter5"},
			{"of3a2", "op4chapter5"},
			{"of3a4", "op4chapter6"},
			{"of3a5", "op4chapter6"},
			{"of3a6", "op4chapter6"},
			{"of4a1", "op4chapter7"},
			{"of4a2", "op4chapter7"},
			{"of4a3", "op4chapter7"},
			{"of4a4", "op4chapter8"},
			{"of4a5", "op4chapter8"},
			{"of5a1", "op4chapter9"},
			{"of5a2", "op4chapter9"},
			{"of5a3", "op4chapter9"},
			{"of5a4", "op4chapter9"},
			{"of6a1", "op4chapter10"},
			{"of6a2", "op4chapter10"},
			{"of6a3", "op4chapter10"},
			{"of6a4", "op4chapter10"},
			{"of6a4b", "op4chapter11"},
			{"of6a5", "op4chapter11"},
			{"of7a0", "op4chapter12"},
			{"ofboot0", "op4chapter13"},
			{"ofboot1", "op4chapter13"},
			{"ofboot2", "op4chapter13"},
			{"ofboot3", "op4chapter13"},
			{"ofboot4", "op4chapter13"},
			{"of0a0", "op4chapter14"},
		};

		const std::unordered_map<std::string_view, std::string> bs_thumbnail_to_chapter = {
			{"bschapter1", "Insecurity"},
			{"bschapter2", "Duty Calls"},
			{"bschapter3", "Captive Freight"},
			{"bschapter4", "Focal Point"},
			{"bschapter5", "Power Struggle"},
			{"bschapter6", "Captive Freight & A Leap of Faith"},
			{"bschapter7", "Outro"},
			{"bschapter8", "Hazard Course"},
			{"bschapter9", "Living Quarters Outbound"},
		};

		const std::unordered_map<std::string_view, std::string> bs_map_name_to_thumbnail = {
			{"ba_security1", "bschapter1"},
			{"ba_security2", "bschapter1"},
			{"ba_maint", "bschapter1"},
			{"ba_elevator", "bschapter1"},
			{"ba_canal1", "bschapter2"},
			{"ba_canal1b", "bschapter2"},
			{"ba_canal2", "bschapter2"},
			{"ba_canal3", "bschapter2"},
			{"ba_yard1", "bschapter3"},
			{"ba_yard2", "bschapter3"},
			{"ba_yard3", "bschapter3"},
			{"ba_yard3a", "bschapter3"},
			{"ba_yard3b", "bschapter3"},
			{"ba_yard4", "bschapter3"},
			{"ba_yard4a", "bschapter3"},
			{"ba_yard5", "bschapter3"},
			{"ba_yard5a", "bschapter3"},
			{"ba_teleport1", "bschapter3"},
			{"ba_xen1", "bschapter4"},
			{"ba_xen2", "bschapter4"},
			{"ba_xen3", "bschapter4"},
			{"ba_xen4", "bschapter4"},
			{"ba_xen5", "bschapter4"},
			{"ba_xen6", "bschapter4"},
			{"ba_power1", "bschapter5"},
			{"ba_power2", "bschapter5"},
			{"ba_teleport2", "bschapter6"},
			{"ba_outro", "bschapter7"},
			{"ba_hazard1", "bschapter8"},
			{"ba_hazard2", "bschapter8"},
			{"ba_hazard3", "bschapter8"},
			{"ba_hazard4", "bschapter8"},
			{"ba_hazard5", "bschapter8"},
			{"ba_hazard6", "bschapter8"},
			{"ba_tram1", "bschapter9"},
			{"ba_tram2", "bschapter9"},
			{"ba_tram3", "bschapter9"},
			{"ba_security1", "bschapter9"},
		};

		const std::unordered_map<std::string_view, std::string> gmc_thumbnail_to_chapter = {
			{"gmcchapter1", "City"},
			{"gmcchapter2", "Mayan"},
			{"gmcchapter3", "Cinematic"},
			{"gmcchapter5", "Cinematic 2"},
			{"gmcchapter6", "West"},
			{"gmcchapter7", "Rebar"},
			{"gmcchapter8", "End"},
			{"gmcchapter9", "Tram Part"},
		};

		const std::unordered_map<std::string_view, std::string> gmc_map_name_to_thumbnail = {
			{"city2a", "gmcchapter1"},
			{"city2b", "gmcchapter1"},
			{"city3a", "gmcchapter1"},
			{"city3b", "gmcchapter1"},
			{"mayan0a", "gmcchapter2"},
			{"mayan0b", "gmcchapter2"},
			{"mayan1", "gmcchapter2"},
			{"mayan3a", "gmcchapter2"},
			{"mayan4", "gmcchapter2"},
			{"mayan6", "gmcchapter2"},
			{"mayan8", "gmcchapter2"},
			{"cinematic1", "gmcchapter3"},
			{"cinematic2", "gmcchapter3"},
			{"rust1", "gmcchapter4a"},
			{"rust2a", "gmcchapter4a"},
			{"rust2b", "gmcchapter4a"},
			{"rust3a", "gmcchapter4a"},
			{"rust4a", "gmcchapter4b"},
			{"rust4b", "gmcchapter4b"},
			{"rust4c", "gmcchapter4b"},
			{"rust5a", "gmcchapter4b"},
			{"rust6a", "gmcchapter4b"},
			{"rust6b", "gmcchapter4b"},
			{"rust6c", "gmcchapter4b"},
			{"rust6d", "gmcchapter4"},
			{"rust7a", "gmcchapter4c"},
			{"rust7b", "gmcchapter4c"},
			{"rust7c", "gmcchapter4c"},
			{"rust7d", "gmcchapter4d"},
			{"rust7e", "gmcchapter4d"},
			{"rust8a", "gmcchapter4d"},
			{"rust9a", "gmcchapter4d"},
			{"cinematic3", "gmcchapter5"},
			{"cinematic4", "gmcchapter5"},
			{"west1", "gmcchapter6"},
			{"west2", "gmcchapter6"},
			{"west3a", "gmcchapter6"},
			{"west3b", "gmcchapter6"},
			{"west4a", "gmcchapter6"},
			{"west4b", "gmcchapter6"},
			{"west5b", "gmcchapter6"},
			{"west6a", "gmcchapter6"},
			{"west6b", "gmcchapter6"},
			{"west6c", "gmcchapter6"},
			{"west6d", "gmcchapter6"},
			{"west6e", "gmcchapter6"},
			{"rebar0a", "gmcchapter7"},
			{"rebar0b", "gmcchapter7"},
			{"rebar2a", "gmcchapter7"},
			{"rebar2b", "gmcchapter7"},
			{"rebar2c", "gmcchapter7"},
			{"rebar2d", "gmcchapter7"},
			{"rebar2e", "gmcchapter7"},
			{"rebar2f", "gmcchapter7"},
			{"rebar2g", "gmcchapter7"},
			{"rebar2h", "gmcchapter7"},
			{"rebar2i", "gmcchapter7"},
			{"rebar2j", "gmcchapter7"},
			{"rebar2k", "gmcchapter7"},
			{"rebar2l", "gmcchapter7"},
			{"rebar3b", "gmcchapter7"},
			{"rebar3d", "gmcchapter7"},
			{"rebar3e", "gmcchapter7"},
			{"end1", "gmcchapter8"},
			{"end2", "gmcchapter8"},
			{"city1a", "gmcchapter9"},
			{"city1b", "gmcchapter9"},
		};

		const std::unordered_map<std::string_view, std::string> czds_thumbnail_to_chapter = {
			{"czdschapter1", "Recoil"},
			{"czdschapter2", "Lost Cause"},
			{"czdschapter3", "Secret War"},
			{"czdschapter4", "Building Recon"},
			{"czdschapter5", "DrugLab"},
			{"czdschapter6", "Motorcade Assault"},
			{"czdschapter7", "Thin Ice"},
			{"czdschapter8", "Downed Pilot"},
			{"czdschapter9", "Hankagai"},
			{"czdschapter10", "Turn of the Crank"},
			{"czdschapter11", "Alamo"},
			{"czdschapter12", "Rise Hard"},
			{"czdschapter13", "Fastline"},
			{"czdschapter14", "Miami Heat"},
			{"czdschapter15", "Pipe Dream"},
			{"czdschapter16", "Run"},
			{"czdschapter17", "Sandstorm"},
			{"czdschapter18", "Truth in Chaos"},
			{"czdschapter19", "CT Training"},
		};

		const std::unordered_map<std::string_view, std::string> czds_map_name_to_thumbnail = {
			{"cz_recoil-intro", "czdschapter1"},
			{"cz_recoil", "czdschapter1"},
			{"cz_recoil2", "czdschapter1"},
			{"cz_lostcause", "czdschapter2"},
			{"cz_lostcause2", "czdschapter2"},
			{"cz_silo01", "czdschapter3"},
			{"cz_silo02", "czdschapter3"},
			{"cz_silo03", "czdschapter3"},
			{"cz_silo04", "czdschapter3"},
			{"cz_silo05", "czdschapter3"},
			{"cz_brecon01", "czdschapter4"},
			{"cz_brecon02", "czdschapter4"},
			{"cz_brecon03", "czdschapter4"},
			{"cz_brecon04", "czdschapter4"},
			{"cz_brecon05", "czdschapter4"},
			{"cz_brecon06", "czdschapter4"},
			{"cz_druglab1", "czdschapter5"},
			{"cz_druglab2", "czdschapter5"},
			{"cz_druglab3", "czdschapter5"},
			{"cz_druglab4", "czdschapter5"},
			{"cz_motor1", "czdschapter6"},
			{"cz_motor2", "czdschapter6"},
			{"cz_motor3", "czdschapter6"},
			{"cz_thinice01", "czdschapter7"},
			{"cz_thinice02", "czdschapter7"},
			{"cz_thinice03", "czdschapter7"},
			{"cz_downed1", "czdschapter8"},
			{"cz_downed2", "czdschapter8"},
			{"cz_downed3", "czdschapter8"},
			{"cz_downed4", "czdschapter8"},
			{"cz_hankagai1", "czdschapter9"},
			{"cz_hankagai2", "czdschapter9"},
			{"cz_hankagai3", "czdschapter9"},
			{"cz_hankagai4", "czdschapter9"},
			{"cz_hankagai5", "czdschapter9"},
			{"cz_turncrank", "czdschapter10"},
			{"cz_turncrank2", "czdschapter10"},
			{"cz_turncrank3", "czdschapter10"},
			{"cz_alamo", "czdschapter11"},
			{"cz_alamo2", "czdschapter11"},
			{"cz_hr01", "czdschapter12"},
			{"cz_hr02", "czdschapter12"},
			{"cz_hr02b", "czdschapter12"},
			{"cz_hr03", "czdschapter12"},
			{"cz_hr04", "czdschapter12"},
			{"cz_hr05", "czdschapter12"},
			{"cz_hr06", "czdschapter12"},
			{"cz_hr07", "czdschapter12"},
			{"cz_end", "czdschapter12"},
			{"cz_fastline1", "czdschapter13"},
			{"cz_fastline2", "czdschapter13"},
			{"cz_fastline3", "czdschapter13"},
			{"cz_fastline4", "czdschapter13"},
			{"cz_miami1", "czdschapter14"},
			{"cz_miami2", "czdschapter14"},
			{"cz_pipedream1", "czdschapter15"},
			{"cz_pipedream2", "czdschapter15"},
			{"cz_pipedream3", "czdschapter15"},
			{"cz_run1", "czdschapter16"},
			{"cz_run2", "czdschapter16"},
			{"cz_run3", "czdschapter16"},
			{"cz_sandstorm", "czdschapter17"},
			{"cz_sandstorm2", "czdschapter17"},
			{"cz_sandstorm3", "czdschapter17"},
			{"cz_sandstorm4", "czdschapter17"},
			{"cz_truth1", "czdschapter18"},
			{"cz_truth2", "czdschapter18"},
			{"cz_truth3", "czdschapter18"},
			{"cz_truth4", "czdschapter18"},
			{"cz_train01", "czdschapter19"},
			{"cz_train02", "czdschapter19"},
			{"cz_train03", "czdschapter19"},
		};

		const std::unordered_map<std::string_view, std::string> wanted_thumbnail_to_chapter = {
			{"wantchapter1", "Redrock Creek"},
			{"wantchapter2", "The Journey"},
			{"wantchapter3", "Breypass"},
			{"wantchapter4", "Lokita Falls"},
			{"wantchapter5", "Serino"},
			{"wantchapter6", "The Border Hills"},
			{"wantchapter7", "Return to Redrock"},
			{"wantchapter8", "Showdown"},
			{"wantchapter9", "Intro"},
			{"wantchapter10", "Training Ranch"},
		};

		const std::unordered_map<std::string_view, std::string> wanted_map_name_to_thumbnail = {
			{"want1", "wantchapter1"},
			{"want2", "wantchapter2"},
			{"want3", "wantchapter2"},
			{"want4", "wantchapter2"},
			{"want5", "wantchapter2"},
			{"want6", "wantchapter2"},
			{"want7", "wantchapter2"},
			{"want8", "wantchapter3"},
			{"want9", "wantchapter3"},
			{"want10", "wantchapter3"},
			{"want11", "wantchapter4"},
			{"want12", "wantchapter4"},
			{"want13", "wantchapter4"},
			{"want14", "wantchapter4"},
			{"want15", "wantchapter4"},
			{"want16", "wantchapter5"},
			{"want17", "wantchapter5"},
			{"want18", "wantchapter5"},
			{"want19", "wantchapter6"},
			{"want20", "wantchapter6"},
			{"want21", "wantchapter6"},
			{"want22", "wantchapter6"},
			{"want23", "wantchapter6"},
			{"want24", "wantchapter6"},
			{"want24a", "wantchapter6"},
			{"want25", "wantchapter6"},
			{"want25a", "wantchapter6"},
			{"want25b", "wantchapter6"},
			{"want25c", "wantchapter6"},
			{"want26", "wantchapter7"},
			{"want27", "wantchapter7"},
			{"want28", "wantchapter7"},
			{"want29", "wantchapter7"},
			{"want30", "wantchapter7"},
			{"want31", "wantchapter7"},
			{"want32", "wantchapter7"},
			{"want33", "wantchapter7"},
			{"want34", "wantchapter7"},
			{"want35", "wantchapter8"},
			{"want36", "wantchapter8"},
			{"want37", "wantchapter8"},
			{"wantintro", "wantchapter9"},
			{"wanttr", "wantchapter10"},
		};

		const std::unordered_map<std::string_view, std::string> echoes_thumbnail_to_chapter = {
			{"echoeschapter1", "Foundation"},
			{"echoeschapter2", "Collapse"},
			{"echoeschapter3", "Ruin"},
			{"echoeschapter4", "Surge"},
			{"echoeschapter5", "Liberation"},
			{"echoeschapter6", "Tabula Rasa"},
			{"echoeschapter7", "Ashes"},
			{"echoeschapter8", "Dust"},
			{"echoeschapter9", "Echoes"},
			{"echoeschapter10", "Intro"},
		};

		const std::unordered_map<std::string_view, std::string> echoes_map_name_to_thumbnail = {
			{"echoes01", "echoeschapter1"},
			{"echoes01a", "echoeschapter1"},
			{"echoes02", "echoeschapter1"},
			{"echoes03", "echoeschapter1"},
			{"echoes04", "echoeschapter2"},
			{"echoes05", "echoeschapter2"},
			{"echoes06", "echoeschapter3"},
			{"echoes07", "echoeschapter3"},
			{"echoes08", "echoeschapter3"},
			{"echoes09", "echoeschapter3"},
			{"echoes09a", "echoeschapter4"},
			{"echoes09b", "echoeschapter4"},
			{"echoes10", "echoeschapter4"},
			{"echoes11", "echoeschapter4"},
			{"echoes12", "echoeschapter4"},
			{"echoes13", "echoeschapter5"},
			{"echoes14", "echoeschapter5"},
			{"echoes14b", "echoeschapter5"},
			{"echoes15", "echoeschapter5"},
			{"echoes16", "echoeschapter5"},
			{"echoes17", "echoeschapter6"},
			{"echoes18", "echoeschapter6"},
			{"echoes19", "echoeschapter6"},
			{"echoes20", "echoeschapter7"},
			{"echoes21", "echoeschapter7"},
			{"echoes22", "echoeschapter7"},
			{"echoes23", "echoeschapter8"},
			{"echoes24", "echoeschapter9"},
			{"echoes00", "echoeschapter10"},
		};

		const std::unordered_map<std::string_view, std::string> caged_thumbnail_to_chapter = {
			{"cagedchapter1", "Scheduled Termination"},
			{"cagedchapter2", "Turret Unwellness"},
			{"cagedchapter3", "The Yard"},
			{"cagedchapter4", "Jet-Boat Escape"},
			{"cagedchapter4a", "Jet-Boat Escape"},
			{"cagedchapter5", "Intro"},
			{"cagedchapter6", "Epilogue: 24 Hours Earlier"},
		};

		const std::unordered_map<std::string_view, std::string> caged_map_name_to_thumbnail = {
			{"caged_1", "cagedchapter1"},
			{"caged_1b", "cagedchapter2"},
			{"caged_1c", "cagedchapter2"},
			{"caged_2", "cagedchapter3"},
			{"caged_3", "cagedchapter4"},
			{"caged_4", "cagedchapter4a"},
			{"caged_0", "cagedchapter5"},
			{"caged_5", "cagedchapter6"},
		};

		const std::unordered_map<std::string_view, std::string> poke646_thumbnail_to_chapter = {
			{"poke646chapter1", "Audion Industries"},
			{"poke646chapter2", "The Sewers"},
			{"poke646chapter3", "Nation City Library"},
			{"poke646chapter4", "Eastend"},
			{"poke646chapter5", "Xen"},
			{"poke646chapter6", "Boot Camp and Training Area"},
		};

		const std::unordered_map<std::string_view, std::string> poke646_map_name_to_thumbnail = {
			{"po_intro", "poke646chapter1"},
			{"po_aud01", "poke646chapter1"},
			{"po_aud02", "poke646chapter1"},
			{"po_aud03", "poke646chapter1"},
			{"po_aud04", "poke646chapter1"},
			{"po_sew01", "poke646chapter2"},
			{"po_sew02", "poke646chapter2"},
			{"po_sew03", "poke646chapter2"},
			{"po_sew04", "poke646chapter2"},
			{"po_sew05", "poke646chapter2"},
			{"po_lib01", "poke646chapter3"},
			{"po_lib02", "poke646chapter3"},
			{"po_lib03", "poke646chapter3"},
			{"po_lib04", "poke646chapter3"},
			{"po_lib05", "poke646chapter3"},
			{"po_lib06", "poke646chapter3"},
			{"po_lib07", "poke646chapter3"},
			{"po_eas01", "poke646chapter4"},
			{"po_eas02", "poke646chapter4"},
			{"po_eas03", "poke646chapter4"},
			{"po_eas04", "poke646chapter4"},
			{"po_eas05", "poke646chapter4"},
			{"po_eas06", "poke646chapter4"},
			{"po_xen01", "poke646chapter5"},
			{"po_haz01", "poke646chapter6"},
			{"po_haz02", "poke646chapter6"},
			{"po_haz03", "poke646chapter6"},
		};

		const std::unordered_map<std::string_view, std::string> paranoia_map_name_to_thumbnail = {
			{"p_army1", "paranoiachapter1"},
			{"p_army2", "paranoiachapter1"},
			{"p_army3", "paranoiachapter1"},
			{"p_army4", "paranoiachapter1"},
			{"p_army5", "paranoiachapter1"},
			{"p_army6", "paranoiachapter1"},
			{"p_army7", "paranoiachapter1"},
			{"p_army8", "paranoiachapter1"},
			{"p_army9", "paranoiachapter1"},
			{"p_army10", "paranoiachapter1"},
			{"p_army11", "paranoiachapter1"},
			{"p_army12", "paranoiachapter1"},
			{"p_army13", "paranoiachapter1"},
			{"p_army14", "paranoiachapter1"},
			{"p_army15", "paranoiachapter1"},
			{"p_army16", "paranoiachapter1"},
			{"p_indust1", "paranoiachapter2"},
			{"p_indust2", "paranoiachapter2"},
			{"p_indust3", "paranoiachapter2a"},
			{"p_indust4", "paranoiachapter2b"},
			{"p_indust5", "paranoiachapter2c"},
			{"p_indust6", "paranoiachapter2d"},
			{"p_indust7", "paranoiachapter2e"},
			{"p_indust8", "paranoiachapter2f"},
			{"p_indust9", "paranoiachapter2g"},
			{"p_indust10", "paranoiachapter2h"},
			{"p_indust11", "paranoiachapter2h"},
			{"p_indust12", "paranoiachapter2i"},
			{"p_indust13", "paranoiachapter2j"},
			{"p_indust14", "paranoiachapter2j"},
			{"p_indust15", "paranoiachapter2k"},
			{"p_indust16", "paranoiachapter2l"},
			{"p_indust17", "paranoiachapter2m"},
			{"p_indust18", "paranoiachapter2m"},
			{"p_bunk1", "paranoiachapter3"},
			{"p_bunk2", "paranoiachapter3a"},
			{"p_bunk3", "paranoiachapter3b"},
			{"p_bunk4", "paranoiachapter3c"},
			{"p_bunk5", "paranoiachapter3d"},
			{"p_bunk6", "paranoiachapter3e"},
			{"p_bunk7", "paranoiachapter3f"},
			{"p_bunk8", "paranoiachapter3g"},
			{"p_bunk9", "paranoiachapter3f"},
			{"p_bunk10", "paranoiachapter3e"},
			{"p_bunk11", "paranoiachapter3c"},
			{"p_bunk12", "paranoiachapter3c"},
			{"p_bunk13", "paranoiachapter3a"},
			{"p_bunk14", "paranoiachapter3h"},
			{"p_bunk15", "paranoiachapter3i"},
			{"p_bunk16", "paranoiachapter3j"},
			{"p_bunk17", "paranoiachapter3k"},
		};

		const std::unordered_map<std::string_view, std::string> twhltower2_thumbnail_to_chapter = {
			{"tower2chapter1", "Start"},
			{"tower2chapter2", "Pest Control"},
			{"tower2chapter3", "Phantom Lab"},
			{"tower2chapter4", "The Tomb"},
			{"tower2chapter5", "Cargo Specimen"},
			{"tower2chapter6", "Food Court"},
			{"tower2chapter7", "Half-Pint"},
			{"tower2chapter8", "Memories"},
			{"tower2chapter9", "Orange Corporation"},
			{"tower2chapter10", "Tele Office"},
			{"tower2chapter11", "Training Course"},
			{"tower2chapter12", "Smash and Grab"},
			{"tower2chapter13", "Saviour?"},
			{"tower2chapter14", "Xen Garden"},
			{"tower2chapter15", "Apartments"},
			{"tower2chapter16", "Not Much Of A Turnabout"},
			{"tower2chapter17", "Headley and Crabb Solicitors"},
			{"tower2chapter18", "Darkwoods Penitentiary"},
			{"tower2chapter19", "Flippant"},
			{"tower2chapter20", "Von Braun"},
			{"tower2chapter21", "Cupid's Queue"},
			{"tower2chapter22", "Trial By Fire"},
			{"tower2chapter23", "Hard Inferno"},
			{"tower2chapter24", "Repechage"},
			{"tower2chapter25", "All Foyered Up"},
			{"tower2chapter26", "Cenodrome XL"},
		};

		const std::unordered_map<std::string_view, std::string> twhltower2_map_name_to_thumbnail = {
			{"tower2_start", "tower2chapter1"},
			{"tower2_jamaican", "tower2chapter2"},
			{"tower2_dolmo", "tower2chapter3"},
			{"tower2_ogdred", "tower2chapter4"},
			{"tower2_psywarvet", "tower2chapter5"},
			{"tower2_truckstop", "tower2chapter6"},
			{"tower2_mrfloyd", "tower2chapter7"},
			{"tower2_zikshadow", "tower2chapter8"},
			{"tower2_drorange", "tower2chapter9"},
			{"tower2_rollbarrel", "tower2chapter10"},
			{"tower2_spikehunter", "tower2chapter11"},
			{"tower2_strider", "tower2chapter12"},
			{"tower2_jamaican2", "tower2chapter13"},
			{"tower2_garden", "tower2chapter14"},
			{"tower2_drorange2", "tower2chapter15"},
			{"tower2_penguin", "tower2chapter16"},
			{"tower2_urby", "tower2chapter17"},
			{"tower2_psywarvet2", "tower2chapter18"},
			{"tower2_2muchvgs", "tower2chapter19"},
			{"tower2_ogdred2", "tower2chapter20"},
			{"tower2_lukkasz323", "tower2chapter21"},
			{"tower2_psywarvet3", "tower2chapter22"},
			{"tower2_zoony", "tower2chapter23"},
			{"tower2_unq", "tower2chapter24"},
			{"tower2_exit", "tower2chapter25"},
			{"tower2_credits", "tower2chapter26"},
		};

		const std::unordered_map<std::string_view, std::string> aomdc_map_name_to_thumbnail = {
			{"training", "aomdcchapter1"},
			{"intro", "aomdcchapter2"},
			{"nightmare", "aomdcchapter3"},
			{"hospital", "aomdcchapter4"},
			{"hospital2", "aomdcchapter5"},
			{"garage", "aomdcchapter6"},
			{"backalley", "aomdcchapter7"},
			{"darkalley", "aomdcchapter8"},
			{"sewer", "aomdcchapter9"},
			{"city", "aomdcchapter10"},
			{"city2", "aomdcchapter11"},
			{"cityx", "aomdcchapter12"},
			{"1ridingcar", "aomdcchapter13"},
			{"1carforest", "aomdcchapter14"},
			{"1afterforest", "aomdcchapter15"},
			{"1angforest", "aomdcchapter16"},
			{"1forhouse", "aomdcchapter17"},
			{"1forest2", "aomdcchapter18"},
			{"1forest3", "aomdcchapter19"},
			{"1heaven1", "aomdcchapter20"},
			{"1heaven2", "aomdcchapter21"},
			{"city3", "aomdcchapter22"},
			{"2sick", "aomdcchapter23"},
			{"2sick2", "aomdcchapter24"},
			{"2sorgarden", "aomdcchapter25"},
			{"2sorgarden2", "aomdcchapter26"},
			{"2arforest", "aomdcchapter27"},
			{"2afterforest", "aomdcchapter15"},
			{"2angforest", "aomdcchapter16"},
			{"2forhouse", "aomdcchapter17"},
			{"2forest2", "aomdcchapter18"},
			{"2forest3", "aomdcchapter19"},
			{"2heaven1", "aomdcchapter20"},
			{"2heaven2", "aomdcchapter21"},
			{"3city2", "aomdcchapter28"},
			{"cityz", "aomdcchapter29"},
			{"3sick", "aomdcchapter23"},
			{"3sick2", "aomdcchapter24"},
			{"3sorgarden", "aomdcchapter25"},
			{"3sorgarden2", "aomdcchapter26"},
			{"3arforest", "aomdcchapter27"},
			{"3afterforest", "aomdcchapter15"},
			{"3angforest", "aomdcchapter16"},
			{"3forhouse", "aomdcchapter17"},
			{"3forest2", "aomdcchapter18"},
			{"3forest3", "aomdcchapter19"},
			{"3heaven1", "aomdcchapter20"},
			{"3heaven2", "aomdcchapter21"},
			{"4mother", "aomdcchapter30"},
		};

		const std::unordered_map<std::string_view, std::string> aomdc_map_name_to_chapter_misc = {
			{"training", "Training"},
			{"city3", "Ending 2, 3 or 4"},
			{"1end", "Ending 1"},
			{"2end", "Ending 2"},
			{"3end", "Ending 3"},
		};

		const std::unordered_map<std::string_view, std::string> hlrats_parasomnia_thumbnail_to_chapter = {
			{"hrpchapter1", "My El Dorado"},
			{"hrpchapter2", "Road to Perdition"},
			{"hrpchapter3", "No Vacancy"},
			{"hrpchapter4", "The Bonehoard"},
			{"hrpchapter5", "Manor of Speaking"},
			{"hrpchapter6", "Poor Quarter"},
			{"hrpchapter7", "Trip the Light Fantastic"},
			{"hrpchapter8", "Final Showdown"},
			{"hrpchapter9", "Aftermath"},
			{"hrpchapter10", "Half-Rats School"},
		};

		const std::unordered_map<std::string_view, std::string> hlrats_parasomnia_map_name_to_thumbnail = {
			{"para1", "hrpchapter1"},
			{"para2", "hrpchapter2"},
			{"para3", "hrpchapter2"},
			{"para3a", "hrpchapter3"},
			{"para3b", "hrpchapter3"},
			{"para3c", "hrpchapter3"},
			{"para3d", "hrpchapter3"},
			{"para4", "hrpchapter3"},
			{"para4a", "hrpchapter3"},
			{"para5", "hrpchapter3"},
			{"para6", "hrpchapter3"},
			{"para7", "hrpchapter4"},
			{"para7a", "hrpchapter4"},
			{"para8", "hrpchapter5"},
			{"para8a", "hrpchapter5"},
			{"para9", "hrpchapter5"},
			{"para9a", "hrpchapter5"},
			{"para10", "hrpchapter6"},
			{"para10a", "hrpchapter6"},
			{"para10b", "hrpchapter6"},
			{"para10c", "hrpchapter6"},
			{"para11", "hrpchapter7"},
			{"para12", "hrpchapter7"},
			{"para13", "hrpchapter8"},
			{"paraout", "hrpchapter9"},
			{"paraschool", "hrpchapter10"},
		};

		const std::unordered_set<std::string> urbicide_maps {
			"urbicide1"s,
			"urbicide2"s,
			"urbicide3"s,
			"urbicide4"s,
			"urbicide5"s,
			"urbicide6"s,
			"urbicide7"s,
			"urbicide8"s,
			"urbicide9"s,
			"urbicide10"s,
			"urbicide11"s
		};

		const std::unordered_map<std::string_view, std::string> th_map_name_to_thumbnail = {
			{"thintro", "thchapter1"},
			{"they1", "thchapter1a"},
			{"they2", "thchapter1b"},
			{"they3", "thchapter1c"},
			{"they4", "thchapter1c"},
			{"they5", "thchapter1d"},
			{"they6", "thchapter1e"},
			{"they7", "thchapter1f"},
			{"they8", "thchapter1f"},
			{"they9", "thchapter1g"},
			{"they10", "thchapter1h"},
			{"they11", "thchapter1i"},
			{"they12", "thchapter1i"},
			{"they13", "thchapter1j"},
			{"they14", "thchapter1k"},
			{"they15", "thchapter1k"},
			{"they16", "thchapter2"},
			{"they17", "thchapter2a"},
			{"they18", "thchapter2a"},
			{"they19", "thchapter2b"},
			{"they20", "thchapter2c"},
			{"they21", "thchapter2d"},
			{"they22", "thchapter2e"},
			{"they23", "thchapter2f"},
			{"they24", "thchapter2g"},
			{"they25", "thchapter2g"},
			{"they26", "thchapter2g"},
			{"they27", "thchapter2h"},
			{"they28", "thchapter2i"},
			{"they29", "thchapter2j"},
			{"they30", "thchapter3"},
			{"they30a", "thchapter3a"},
			{"they31", "thchapter3a"},
			{"they32", "thchapter3b"},
			{"they33", "thchapter3b"},
			{"they34", "thchapter3b"},
			{"they35", "thchapter3c"},
			{"they36", "thchapter3d"},
			{"they37", "thchapter3d"},
			{"they38", "thchapter3e"},
			{"they39", "thchapter3e"},
			{"they40", "thchapter3f"},
			{"they41", "thchapter3g"},
			{"they42", "thchapter3h"},
			{"they43", "thchapter3h"},
			{"they44", "thchapter3i"},
			{"they45", "thchapter3d"},
			{"they46", "thchapter3j"},
			{"they47", "thchapter3k"},
			{"they48", "thchapter3g"},
			{"they49", "thchapter3l"},
			{"they50", "thchapter3m"},
			{"they51", "thchapter3n"},
			{"they52", "thchapter3o"},
			{"they53", "thchapter3p"},
			{"they54", "thchapter3g"},
			{"they55", "thchapter3p"},
			{"they56", "thchapter3p"},
		};
}
